package com.ecdat.backend.input.security;

/**
 * Error codes for repository analysis operations.
 */
public enum RepositoryErrorCode {
    INVALID_REPOSITORY_URL,
    UNSUPPORTED_REPOSITORY_PROTOCOL,
    REPOSITORY_HOST_BLOCKED,
    REPOSITORY_ACCESS_DENIED,
    REPOSITORY_NOT_FOUND,
    REPOSITORY_TIMEOUT,
    REPOSITORY_LIMIT_EXCEEDED,
    REPOSITORY_CLONE_FAILED,
    REPOSITORY_ANALYSIS_FAILED,
    UNSUPPORTED_REPOSITORY_CONTENT,
    REPOSITORY_TOOL_UNAVAILABLE
}
